services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  catalogdb:
    image: postgres

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  basketdb:
    image: postgres

  distributed_basket_cache:
    image: redis

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

  orderdb:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: rabbitmq:management

volumes:
  postgres_catalog:
  postgres_basket: