GRPC grpcs://{{ServiceHost}}:{{ServicePort}}/discount.DiscountProtoService/GetDiscount

{
  "productName": "Product1"
}

###
GRPC grpcs://{{ServiceHost}}:{{ServicePort}}/discount.DiscountProtoService/CreateDiscount

{
  "coupon": {
    "amount" : 1200,
    "productName": "new",
    "description": "description"
  }
}