services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile

  catalogdb:
    image: postgres
    
  basketdb:
    image: postgres
    
  distributed_basket_cache:
    image: redis

volumes:
  postgres_catalog:
  postgres_basket: