### POST request
POST https://{{ServiceHost}}:{{ServicePort}}/products
Content-Type: application/json

{
  "Name": "New Product",
  "Category": ["c1", "c2"],
  "Description": "New Product Description",
  "ImageFile": "ImageFile Product",
  "Price": 100
}

### GET query
GET https://{{ServiceHost}}:{{ServicePort}}/products

### GET query by id
GET https://{{ServiceHost}}:{{ServicePort}}/products/01953286-fb4a-4a43-a727-f21d8a6a81dd

### GET query by category
GET https://{{ServiceHost}}:{{ServicePort}}/products/category/c2

### PUT request
PUT https://{{ServiceHost}}:{{ServicePort}}/products
Content-Type: application/json

{
  "Id": "01953286-fb4a-4a43-a727-f21d8a6a81dd",
  "Name": "New Product Updated",
  "Category": ["c1", "c2"],
  "Description": "New Product Description Updated",
  "ImageFile": "ImageFile Product Updated",
  "Price": 200
}